server:
  port: 8080
  # 에러 발생 시 상세 내용 숨김 (보안용, 디버깅 시 always로 변경)
  error:
    include-message: never
    include-binding-errors: never
  # 한글 깨짐 방지
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: dosa

  # [S3 설정] 환경변수 사용
  cloud:
    aws:
      s3:
        bucket: "dosa-3d-models"
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-5-mini
  api:
    url: https://api.openai.com/v1/chat/completions