spring:
  application:
    name: dosa

  datasource:
    url: jdbc:mysql://localhost:3306/dosa_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 해커톤용: 엔티티 수정하면 DB 테이블 자동 변경 (실무에선 validate/none 사용)
    properties:
      hibernate:
        format_sql: true # 실행되는 SQL을 예쁘게 보여줌
        show_sql: true   # 실행되는 SQL을 로그에 찍음
    open-in-view: false

  # 한글 깨짐 방지
  server:
    servlet:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    port: ${SERVER_PORT:8080}

  cloud:
    aws:
      s3:
        bucket: "dosa-3d-models"  # 아까 만든 버킷 이름
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2