spring:
  application:
    name: dosa

  # [S3 설정] 환경변수 사용
  cloud:
    aws:
      s3:
        bucket: "dosa-3d-models"
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2

# [수정] server 설정은 spring 밖으로(맨 왼쪽으로) 빼야 합니다!
server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true